/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import BO.ContextoLivro;
import DAO.DAOUsuario;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class AtualizacaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public AtualizacaoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSenha = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldReg = new javax.swing.JTextField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldSenha.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldSenha.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 250, 30));

        jTextFieldNome.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldNome.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 250, 30));

        jTextFieldReg.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldReg.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 250, 30));

        jTextFieldSobrenome.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldSobrenome.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 250, 30));

        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 300, 50));

        atualizar.setContentAreaFilled(false);
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atualizacaoUsuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSobrenomeActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
    if(    jTextFieldSobrenome.getText().isEmpty() || jTextFieldReg.getText().isEmpty()
        || jTextFieldSenha.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    } else if(!jTextFieldReg.getText().matches("\\d*")) {
        JOptionPane.showMessageDialog(null, "Preencha o campo Registro Academico apenas com caracteres numéros!");
    } else {
        String sobrenome = jTextFieldSobrenome.getText();
        String nome = jTextFieldNome.getText();
        int reg = Integer.parseInt(jTextFieldReg.getText());
        String senha = jTextFieldSenha.getText();
        DAOUsuario daoUsuario = new DAOUsuario();
        Usuario usuario = new Usuario(nome, sobrenome, senha, reg);
        usuario.setId(ContextoLivro.getIdAtual());
        daoUsuario.atualizar(usuario);
        UsuarioEspecifico telaUsuario = new UsuarioEspecifico(usuario);
        telaUsuario.setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_atualizarActionPerformed

    private void jTextFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TelaUsuarios telaUsuario = new TelaUsuarios();
        telaUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void jTextFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton atualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldReg;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
