/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import BO.ContextoLivro;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class AtualizacaoLivro extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public AtualizacaoLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldNumeroDePags = new javax.swing.JTextField();
        jTextFieldEditora = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Prox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldTitulo.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldTitulo.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 250, 30));

        jTextFieldNumeroDePags.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldNumeroDePags.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldNumeroDePags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroDePagsActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumeroDePags, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 250, 30));

        jTextFieldEditora.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldEditora.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditoraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 250, 30));

        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 300, 50));

        Prox.setContentAreaFilled(false);
        Prox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProxActionPerformed(evt);
            }
        });
        getContentPane().add(Prox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atualizacaoDeLivro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditoraActionPerformed

    private void ProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProxActionPerformed
    if(    jTextFieldEditora.getText().isEmpty() || jTextFieldTitulo.getText().isEmpty()
        || jTextFieldNumeroDePags.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    } else if(!jTextFieldNumeroDePags.getText().matches("\\d*")) {
        JOptionPane.showMessageDialog(null, "Preencha o campo Número de Páginas apenas com caracteres numéros!");
    } else {
        String editora = jTextFieldEditora.getText();
        String titulo = jTextFieldTitulo.getText();

        try {
            int numPaginas = Integer.parseInt(jTextFieldNumeroDePags.getText());

            // Define os valores nas variáveis estáticas da classe ContextoLivro
            ContextoLivro.setTituloLivroCadastrado(titulo);
            ContextoLivro.setPaginasLivroCadastrado(numPaginas);
            ContextoLivro.setEditoraLivroCadastrado(editora);

            AtualizacaoLivroAutor cadastroLivroAutor = new AtualizacaoLivroAutor();
            cadastroLivroAutor.setVisible(true);
            dispose();
        } catch (NumberFormatException e) {
            // Tratar o erro caso a conversão não seja possível
            System.err.println("Erro: Número de páginas inválido.");
        }
    }
    }//GEN-LAST:event_ProxActionPerformed

    private void jTextFieldNumeroDePagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDePagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroDePagsActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TelaOpcoesAdmin telaAdmin = new TelaOpcoesAdmin();
        telaAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Prox;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldNumeroDePags;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
