/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DAOEmprestimo;
import Modelo.Date;
import java.text.SimpleDateFormat;
import BO.Contexto;
import DAO.DAOLivro;
import DAO.DAOUsuario;
import Modelo.Emprestimo;
import Modelo.Livro;
import Modelo.Usuario;
import java.text.ParseException;
import javax.swing.JOptionPane;


/**
 *
 * @author maria
 */
public class CadastroEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CadastroEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldData = new javax.swing.JTextField();
        jTextFieldReg = new javax.swing.JTextField();
        jTextFieldIdLivro = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldData.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldData.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 250, 30));

        jTextFieldReg.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldReg.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 250, 30));

        jTextFieldIdLivro.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldIdLivro.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldIdLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdLivroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 250, 30));

        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 300, 50));

        jButtonCadastrar.setContentAreaFilled(false);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroEmprestimo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void jTextFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegActionPerformed

    private void jTextFieldIdLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdLivroActionPerformed

    private void limparCampos() {
        jTextFieldData.setText("");
        jTextFieldIdLivro.setText("");
        jTextFieldReg.setText("");
    }
    
    private void cadastrarEmprestimo() {
        if(    jTextFieldData.getText().isEmpty() || jTextFieldIdLivro.getText().isEmpty()
            || jTextFieldReg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else if(!jTextFieldReg.getText().matches("\\d*")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Registro Academico apenas com caracteres numéros!");
        } else if(!jTextFieldIdLivro.getText().matches("\\d*")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Id Livro apenas com caracteres numéros!");
        } else {
            String dataString = jTextFieldData.getText();
            int idLivro = Integer.parseInt(jTextFieldIdLivro.getText());
            int reg = Integer.parseInt(jTextFieldReg.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date data = null; 

            try {
                java.util.Date utilDate = sdf.parse(dataString);
                int dia = utilDate.getDate();
                int mes = utilDate.getMonth() + 1;
                int ano = utilDate.getYear() + 1900;
                data = new Modelo.Date(dia, mes, ano);
            } catch (ParseException e) {
                // Tratar erro de parsing de data
                e.printStackTrace();
                return; // Não prosseguir com o empréstimo se houver erro de parsing
            }

            DAOEmprestimo daoEmp = new DAOEmprestimo();
            DAOLivro daoLivro = new DAOLivro(); 
            // Verificar se o livro com o ID fornecido existe
            Livro livro = daoLivro.localizar(idLivro);
            if (livro == null) {
                JOptionPane.showMessageDialog(this, "Livro não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                limparCampos();
                return; // Não prosseguir com o empréstimo
            }
            if(!daoLivro.estaDisponivel(idLivro)){
                JOptionPane.showMessageDialog(this, "Livro não está disponível!", "Erro", JOptionPane.ERROR_MESSAGE);
                limparCampos();
                return; // Não prosseguir com o empréstimo
            }
            DAOUsuario daoUsuario = new DAOUsuario();
            // Verificar se o aluno com o registro fornecido existe
            Usuario usuario = daoUsuario.localizar(reg);
            if (usuario == null) {
                JOptionPane.showMessageDialog(this, "Aluno não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                limparCampos();
                return; // Não prosseguir com o empréstimo
            }

            // Criar o objeto Emprestimo e realizar a inclusão
            Emprestimo emprestimo = new Emprestimo(Contexto.getId(), reg, idLivro, data);
            daoEmp.incluir(emprestimo);
            DAOLivro.emprestimo(idLivro);

            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            TelaOpcoesFunc tela = new TelaOpcoesFunc();
            tela.setVisible(true);
            dispose();
        }
    }

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarEmprestimo();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        TelaOpcoesFunc tela = new TelaOpcoesFunc();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldIdLivro;
    private javax.swing.JTextField jTextFieldReg;
    // End of variables declaration//GEN-END:variables
}
