/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import BO.ContextoLivro;
import DAO.DAOAutor;
import javax.swing.JPanel;
import Modelo.Autor;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author maria
 */
public class CadastroLivroAutorr extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private List<Autor> autoresSelecionados = new ArrayList<>();

    public CadastroLivroAutorr() {
        initComponents();
        gerarAutores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Proxima = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Proxima.setContentAreaFilled(false);
        Proxima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximaActionPerformed(evt);
            }
        });
        getContentPane().add(Proxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 300, 50));

        Voltar.setContentAreaFilled(false);
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CadastroLivro2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximaActionPerformed
        // TODO add your handling code here:
        ContextoLivro.setAutorLivroCadastrado(autoresSelecionados);
        CadastroLivroCat cadastroLivroCat = new CadastroLivroCat();
        cadastroLivroCat.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProximaActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        CadastroLivro telaAnterior = new CadastroLivro();
        telaAnterior.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed
    
    private void gerarAutores() {
    JPanel panel = new JPanel(new GridLayout(0, 1));
    DAOAutor daoAutor = new DAOAutor();
    List<Autor> autores = daoAutor.getList();
    for (Autor autor : autores) {
        JCheckBox checkBox = new JCheckBox(autor.getNome() + " " + autor.getSobreNome());

        checkBox.addActionListener(e -> {
            if (checkBox.isSelected()) {
                autoresSelecionados.add(autor);
            } else {
                autoresSelecionados.remove(autor);
            }
        });

        panel.add(checkBox);
    }

    getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 300, -1));


    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroAutorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroAutorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroAutorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroAutorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivroAutorr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proxima;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
