/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DAOEmprestimo;
import DAO.DAOLivro;
import Modelo.Emprestimo;
import javax.swing.JOptionPane;


/**
 *
 * @author maria
 */
public class emprestimoRecebido extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public emprestimoRecebido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIdLivro = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonReceber = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIdLivro.setBackground(new java.awt.Color(143, 142, 142));
        jTextFieldIdLivro.setFont(new java.awt.Font("Garuda", 0, 18)); // NOI18N
        jTextFieldIdLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdLivroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 250, 30));

        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 300, 50));

        jButtonReceber.setContentAreaFilled(false);
        jButtonReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceberActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReceber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emprestimoRecebido.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdLivroActionPerformed

    private void limparCampos() {
        jTextFieldIdLivro.setText("");
    }
    
    private void receber(){
        if(    jTextFieldIdLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo!");
        } else if(!jTextFieldIdLivro.getText().matches("\\d*")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Id Livro apenas com caracteres numéros!");
        } else {
            int idLivro = Integer.parseInt(jTextFieldIdLivro.getText());
            DAOEmprestimo daoEmp = new DAOEmprestimo();
            Emprestimo emprestimo = daoEmp.localizar(idLivro);
            daoEmp.remover(emprestimo);
            DAOLivro.receberLivro(idLivro);
            JOptionPane.showMessageDialog(this, "Livro recebido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            TelaOpcoesFunc tela = new TelaOpcoesFunc();
            tela.setVisible(true);
            dispose();
        }
    }
    
    private void jButtonReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceberActionPerformed
        // TODO add your handling code here:
        receber();
    }//GEN-LAST:event_jButtonReceberActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        TelaOpcoesFunc tela = new TelaOpcoesFunc();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emprestimoRecebido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emprestimoRecebido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emprestimoRecebido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emprestimoRecebido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emprestimoRecebido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReceber;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldIdLivro;
    // End of variables declaration//GEN-END:variables
}
