/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DAOAutor;
import DAO.DAOCategoria;
import DAO.DAOFuncionário;
import DAO.DAOLivro;
import DAO.DAOUsuario;
import Modelo.Autor;
import Modelo.Categoria;
import Modelo.Funcionario;
import Modelo.Livro;
import Modelo.Usuario;

/**
 *
 * @author maria
 */
public class Login extends javax.swing.JFrame {
    public void populacao(){
        Usuario user1 = new Usuario("8","8", "8", 8);
        DAOUsuario u = new DAOUsuario();
        u.incluir(user1);
        Funcionario func1 = new Funcionario("9","9", 9, "9");
        DAOFuncionário f = new DAOFuncionário();
        f.incluir(func1);
        DAOCategoria c = new DAOCategoria();
        DAOAutor a = new DAOAutor();
        DAOLivro l = new DAOLivro();
        Categoria cat = new Categoria("mari feia");
        Categoria cat2 = new Categoria("mari feia");
        Autor aut = new Autor("maria", "bessa", "linda");
        a.incluir(aut);
        c.incluir(cat);
        c.incluir(cat2);
        for(int i = 0; i < 30; i++){
            Livro livro = new Livro("mari feia " + i, "global", 100,c.getList(),a.getList());
            l.incluir(livro);
        }
    }
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entrar = new javax.swing.JButton();
        EntrarAdmin = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrar.setContentAreaFilled(false);
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 260, 50));

        EntrarAdmin.setContentAreaFilled(false);
        EntrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(EntrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 260, 50));

        Sair.setContentAreaFilled(false);
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
        LoginConta loginDoUsuario = new LoginConta();
        loginDoUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_EntrarActionPerformed

    private void EntrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarAdminActionPerformed
        // TODO add your handling code here:
        TelaOpcoesAdmin telaDeAdministrador = new TelaOpcoesAdmin();
        telaDeAdministrador.setVisible(true);
        dispose();
    }//GEN-LAST:event_EntrarAdminActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
                //Login login = new Login();
        //login.populacao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JButton EntrarAdmin;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
